### ISSUE TITLE
renko wicks

### ISSUE THREAD

**Issue by rrfaria** [quantroom-pro/pyrenko#2]
How can I implement renko wicks like tradingview site

**Comment by rrfaria** [comment]
I found this one in js maybe can be useful
https://gist.github.com/MrHerickS/52929335b40780186d49fd65d2cc5489

**Comment by lamres** [comment]
Hi.
Can you explain your suggestion with details?

**Comment by lamres** [comment]
Hi.
Can you explain your suggestion with details?

**Comment by rrfaria** [comment]
I guess it could be good to explain what renko wicks are:

https://www.tradingview.com/blog/en/wicks-renko-charts-now-available-4879/
https://www.linnsoft.com/support/can-you-explain-what-wicks-or-tails-renko-charts-represent

Those articles explain what are renko wicks.

**Comment by xazuakine** [comment]
Sergey, thanks for the perfect essay on https://towardsdatascience.com/renko-brick-size-optimization-34d64400f60e ....
As rrfaria mentiond on the post wicks are important aspects to determine the strenght of reversal move according to choosen brick size. Links are perfectly describes.
It could be great if you manage to implement it in your code.
Thanks for the good work.

**Comment by jamienjoroge** [comment]
trying to pip install 
 `pip install git+https://github.com/quantroom-pro/pyrenko.git@master` 
but gets the error file not found any help?

**Comment by lamres** [comment]
@jamienjoroge I answered the similar questions here https://github.com/quantroom-pro/pyrenko/issues/3

This module is not prepared for "pip install", you should copy and paste the main file to your directory.

**Comment by jamienjoroge** [comment]
trying to run i get 
`Traceback (most recent call last):
  File "historicalrenko.py", line 71, in <module>
    renko_obj_atr.plot_renko()
  File "/home/james/Jamie/iqoption-bot/pyrenko.py", line 146, in plot_renko
    self.ax.clear()
AttributeError: module 'matplotlib.pyplot' has no attribute 'clear'`
any help

**Comment by engviniciusfernandes** [comment]
Do you have a code that can calculate the volume and the OHLC data of each brick? Thanks.

**Comment by lamres** [comment]
@engviniciusfernandes 
Hi.
Unfortunately, this functionality is not supported, but a similar question was asked earlier
https://github.com/quantroom-pro/pyrenko/issues/1

**Comment by cloudi5development** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
